# Generated by Django 4.2.9 on 2024-11-01 09:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='festivalActivities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('estimated_date', models.CharField(max_length=200)),
                ('in_outDoor', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('photo_main', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
