# Generated by Django 4.2.9 on 2024-11-01 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryActivities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('content_more', django_ckeditor_5.fields.CKEditor5Field()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('maplink', models.URLField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('monday', models.CharField(max_length=200)),
                ('tuesday', models.CharField(max_length=200)),
                ('wednesday', models.CharField(max_length=200)),
                ('thursday', models.CharField(max_length=200)),
                ('friday', models.CharField(max_length=200)),
                ('saturday', models.CharField(max_length=200)),
                ('sunday', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('heritage', 'Cultural Heritage'), ('nature', 'Nature and Scenery'), ('culinary', 'Culinary Excellence'), ('festival', 'Festivals and Events'), ('arts', 'Arts and Culture'), ('crafts', 'Local Crafts and Souvenirs'), ('landmark', 'Unique Landmark and Experiences'), ('adventure', 'Adventures'), ('mall', 'Shopping Malls'), ('street', 'Streets and Night markets'), ('museum', 'Museums'), ('restaurant', 'Restaurants and Cafes')], max_length=200)),
                ('fee', models.CharField(max_length=200)),
                ('in_outDoor', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('photo_main', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
